services:
  api:
    build:
      context: .
      dockerfile: ./backend/api/Dockerfile
    image: highwater-api
    container_name: highwater-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    networks:
      - highwater-network
    restart: unless-stopped

  web:
    pull_policy: build
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: highwater-web
    container_name: highwater-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # - NEXT_PUBLIC_API_URL=http://api:4000
    # depends_on:
    #   - api
    # volumes:
    #   - ./frontend:/app/
    #   - ./shared/ts:/app/node_modules/@highwater
    networks:
      - highwater-network
    restart: unless-stopped

networks:
  highwater-network:
    driver: bridge
