version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: highwater/api
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./packages/api:/app/api
      - ./packages/types:/app/packages/types

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: highwater/web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./packages/web:/app/web
      - ./packages/types:/app/packages/types
