version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: highwater/api
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules

  web:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: highwater/web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
