version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./api:/app
    working_dir: /app
    command: ["npm", "run", "dev"]

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./web:/app
    working_dir: /app
    command: ["npm", "run", "dev"]

  test:
    image: node:20-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: ["sh", "-c", "sleep 3600s"]
